baseURL = "https://dekapitalist.github.io/kapitalist/"
languageCode = "nl-be"
title = "De Kapitalist"
theme = "PaperMod"

enableRobotsTXT = true
paginate = 10

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[params]
description = "Blog over investeren, vermogensopbouw, slim omgaan met geld om uiteindelijk financiële vrijheid te hebben."
author = "De Kapitalist"
ShowReadingTime = true
ShowShareButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true

