site_url: https://dekapitalist.github.io/kapitalist
  
backend:
  name: github
  repo: dekapitalist/kapitalist
  branch: main
  base_url: https://decap-auth.barres-70-nouveau-546.workers.dev
  auth_endpoint: auth

media_folder: "static/images"
public_folder: "/kapitalist/images"

collections:
- name: "posts"
  label: "Blog posts"
  folder: content/posts
  slug: "{{year}}/{{slug}}"
  create: true
  fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
