backend:
  name: github
  repo: dekapitalist/kapitalist
  branch: main
  base_url: https://api.github.com

media_folder: "static/images"
public_folder: "/images"

collections:

- name: "posts"
  label: "Blog posts"
  folder: "content/posts"
  create: true
  path: "{{year}}/{{slug}}"

  fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
